# Generated by Django 5.1.6 on 2025-02-18 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyf_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='academics',
        ),
        migrations.RemoveField(
            model_name='areaofinterest',
            name='person',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='education',
            name='person',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='professionalskills',
            name='person',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='person',
        ),
        migrations.RemoveField(
            model_name='projectorjob',
            name='person',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('pen_name', models.CharField(max_length=250)),
                ('profile_photo', models.ImageField(upload_to='profile_photo/')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='projects/covers/')),
                ('content_url', models.FileField(upload_to='projects/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skill_id', models.ManyToManyField(to='fyf_app.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyf_app.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyf_app.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyf_app.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyf_app.projects')),
            ],
        ),
        migrations.DeleteModel(
            name='Academics',
        ),
        migrations.DeleteModel(
            name='AreaOfInterest',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='ProfessionalSkills',
        ),
        migrations.DeleteModel(
            name='ProjectOrJob',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
