# Generated by Django 5.1.6 on 2025-03-16 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyf_app', '0003_joblisting_resumetemplate_remove_like_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
